In [2]:
import pandas as pd

In [3]:
import ast

In [4]:
movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

In [5]:
print("Movies:", movies.shape)
print("Credits:", credits.shape)

Movies: (4803, 20)
Credits: (4803, 4)

In [6]:
print(movies.columns)
print(credits.columns)

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='str')
Index(['movie_id', 'title', 'cast', 'crew'], dtype='str')

In [7]:
movies.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [8]:
credits.isnull().sum()

movie_id    0
title       0
cast        0
crew        0
dtype: int64

In [9]:
credits.duplicated().sum()

np.int64(0)

In [10]:
movies.duplicated().sum()

np.int64(0)

In [11]:
movies[['title', 'genres', 'keywords', 'overview',
        'runtime', 'original_language',
        'vote_average', 'vote_count']].head()

,title,genres,keywords,overview,runtime,original_language,vote_average,vote_count
0,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",162.0,en,7.2,11800
1,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",169.0,en,6.9,4500
2,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,148.0,en,6.3,4466
3,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,165.0,en,7.6,9106
4,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...",132.0,en,6.1,2124

In [12]:
movies = movies[
    ['id',
     'title',
     'genres',
     'keywords',
     'overview',
     'runtime',
     'original_language',
     'vote_average',
     'vote_count']
]

In [13]:
credits = credits[
    ['movie_id',
     'title',
     'cast',
     'crew']
]

In [14]:
movies.columns

Index(['id', 'title', 'genres', 'keywords', 'overview', 'runtime',
       'original_language', 'vote_average', 'vote_count'],
      dtype='str')

In [15]:
credits.columns

Index(['movie_id', 'title', 'cast', 'crew'], dtype='str')

In [16]:
movies.isnull().sum()

id                   0
title                0
genres               0
keywords             0
overview             3
runtime              2
original_language    0
vote_average         0
vote_count           0
dtype: int64

In [17]:
movies['overview'] = movies['overview'].fillna('')

In [18]:
movies['runtime'] = movies['runtime'].fillna(movies['runtime'].median())

In [19]:
movies.isnull().sum()

id                   0
title                0
genres               0
keywords             0
overview             0
runtime              0
original_language    0
vote_average         0
vote_count           0
dtype: int64

In [20]:
credits.isnull().sum()

movie_id    0
title       0
cast        0
crew        0
dtype: int64

In [21]:
movies = movies.merge(
    credits,
    left_on='id',
    right_on='movie_id'
)

In [22]:
movies.shape

(4803, 13)

In [23]:
movies.columns

Index(['id', 'title_x', 'genres', 'keywords', 'overview', 'runtime',
       'original_language', 'vote_average', 'vote_count', 'movie_id',
       'title_y', 'cast', 'crew'],
      dtype='str')

In [24]:
movies.drop(['title_y', 'movie_id'], axis=1, inplace=True)

In [25]:
movies.rename(columns={'title_x': 'title'}, inplace=True)

In [26]:
movies.columns

Index(['id', 'title', 'genres', 'keywords', 'overview', 'runtime',
       'original_language', 'vote_average', 'vote_count', 'cast', 'crew'],
      dtype='str')

In [27]:
movies.to_csv("smartmovie_dataset.csv", index=False)

In [28]:
movies[['title', 'genres', 'keywords', 'cast', 'crew']].head()

,title,genres,keywords,cast,crew
0,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [29]:
def convert_names(text):
    result = []
    
    for item in ast.literal_eval(text):
        result.append(item['name'])
        
    return result

In [30]:
movies['genres'] = movies['genres'].apply(convert_names)
movies['keywords'] = movies['keywords'].apply(convert_names)

In [31]:
movies[['title', 'genres', 'keywords']].head()

,title,genres,keywords
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon..."
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ..."
2,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi..."
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i..."
4,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel..."

In [32]:
def convert_cast(text):
    result = []
    
    for item in ast.literal_eval(text)[:3]:
        result.append(item['name'])
        
    return result

In [33]:
movies['cast'] = movies['cast'].apply(convert_cast)

In [34]:
movies[['title', 'cast']].head()

,title,cast
0,Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]"
1,Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley]"
2,Spectre,"[Daniel Craig, Christoph Waltz, Léa Seydoux]"
3,The Dark Knight Rises,"[Christian Bale, Michael Caine, Gary Oldman]"
4,John Carter,"[Taylor Kitsch, Lynn Collins, Samantha Morton]"

In [35]:
def get_director(text):
    for item in ast.literal_eval(text):
        if item['job'] == 'Director':
            return item['name']
    
    return ''

In [36]:
movies['director'] = movies['crew'].apply(get_director)

In [37]:
movies[['title', 'director']].head()

                                      title           director
0                                    Avatar      James Cameron
1  Pirates of the Caribbean: At World's End     Gore Verbinski
2                                   Spectre         Sam Mendes
3                     The Dark Knight Rises  Christopher Nolan
4                               John Carter     Andrew Stanton

In [38]:
movies.drop('crew', axis=1, inplace=True)

In [39]:
movies['overview'] = movies['overview'].apply(lambda x: x.split())

In [40]:
movies['genres'] = movies['genres'].apply(
    lambda x: [i.replace(" ", "") for i in x]
)
movies['keywords'] = movies['keywords'].apply(
    lambda x: [i.replace(" ", "") for i in x]
)
movies['cast'] = movies['cast'].apply(
    lambda x: [i.replace(" ", "") for i in x]
)
movies['director'] = movies['director'].apply(
    lambda x: x.replace(" ", "")
)

In [41]:
movies['tags'] = (
    movies['overview']
    + movies['genres']
    + movies['keywords']
    + movies['cast']
    + movies['director'].apply(lambda x: [x])
)

In [42]:
movies[['title', 'tags']].head()

,title,tags
0,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [43]:
movies['tags'] = movies['tags'].apply(lambda x: " ".join(x))

In [44]:
print(type(movies['tags'][0]))

<class 'str'>

In [45]:
movies['tags'] = (
    movies['overview']
    + movies['genres']
    + movies['keywords']
    + movies['cast']
    + movies['director'].apply(lambda x: [x])
)

In [46]:
movies['tags'] = movies['tags'].apply(lambda x: " ".join(x))

In [47]:
movies['tags'] = movies['tags'].apply(lambda x: x.lower())

In [48]:
movies[['title', 'tags']].head(2)

,title,tags
0,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."

In [49]:
movies['director'] = movies['director'].fillna('')

In [50]:
movies.isnull().sum()

id                   0
title                0
genres               0
keywords             0
overview             0
runtime              0
original_language    0
vote_average         0
vote_count           0
cast                 0
director             0
tags                 0
dtype: int64

In [51]:
movies.to_csv("smartmovie_preprocessed.csv", index=False)

In [52]:
movies['director'] = movies['director'].fillna('unknown')

In [53]:
movies['director'].isnull().sum()

np.int64(0)

In [54]:
movies['tags'] = (
    movies['overview']
    + movies['genres']
    + movies['keywords']
    + movies['cast']
    + movies['director'].apply(lambda x: [x])
)

In [55]:
movies['tags'] = movies['tags'].apply(lambda x: " ".join(x))

In [56]:
movies['tags'] = movies['tags'].str.lower()

In [57]:
print(movies['director'].isnull().sum())
print(movies['tags'].isnull().sum())

0
0

In [58]:
movies[['title', 'director', 'tags']].head()

,title,director,tags
0,Avatar,JamesCameron,"in the 22nd century, a paraplegic marine is di..."
1,Pirates of the Caribbean: At World's End,GoreVerbinski,"captain barbossa, long believed to be dead, ha..."
2,Spectre,SamMendes,a cryptic message from bond’s past sends him o...
3,The Dark Knight Rises,ChristopherNolan,following the death of district attorney harve...
4,John Carter,AndrewStanton,"john carter is a war-weary, former military ca..."

In [59]:
movies.to_csv("smartmovie_preprocessed.csv", index=False)

In [60]:
print(movies['director'].isnull().sum())

movies['director'] = movies['director'].fillna('unknown')

print(movies['director'].isnull().sum())

0
0